---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: collegemicroservice05oct
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: collegemicroservice05oct
    spec:
      containers:
      - name: collegemicroservice05oct
        image: vishipayyallore/collegeapi-oct05v2
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
---
apiVersion: v1
kind: Service
metadata:
  name: collegemicroservice05oct
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: collegemicroservice05oct